#!/bin/bash

# Store the output temporarily 
release=$(gh release list --json name,tagName --limit 1)

# Extract values using 'jq' for JSON parsing
name=$(echo $release | jq -r '.[0].name')
tagName=$(echo $release | jq -r '.[0].tagName')

# Delete the latest release
gh release delete "$name"
git tag -d $tagName

git tag $tagName
gh release create $tagName -p --generate-notes