name: Build release assets

on:
  release:
    types:
      - created

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} ${{ matrix.customParameters }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
        customParameters: 
          - ""
          - "-EnableHeadlessMode"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ github.event.release.tag }}
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: ${{ matrix.customParameters }}
      - uses: vimtor/action-zip@v1
        with:
          files: build/
          recursive: false
          dest: ${{ matrix.targetPlatform }}${{ matrix.customParameters }}.zip
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.targetPlatform }}${{ matrix.customParameters }}.zip