name: Build Virtu-ALS
on: 
  push:
    branches:
      - master
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  prepare_release:
    name: Create a release draft for artifacts to be attached to
    runs-on: ubuntu-latest
    outputs:
      releaseUrl: ${steps.release.outputs.upload_url}
    steps:
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} ${{ matrix.customParameters }}
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
        customParameters: 
          - ""
          - "-EnableHeadlessMode"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: ${{ matrix.customParameters }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.prepare_release.outputs.releaseUrl }}
          asset_name: Build-${{ matrix.targetPlatform }}${{ matrix.customParameters }}
          asset_path: build/${{ matrix.targetPlatform }}